service: sqs-example

custom:
  id: --Add Id Cloud
  region: --Add Region

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.region}
  role: --Add role with SQS and SSM permissions or more services if needed
  tags:
    projectName: sqs-example
    environment: ${opt:stage}
  memorySize: 256
  timeout: 30

functions:
  dispatchMail:
    handler: src/dispatch.handler
    events:
      - http:
          method: post
          path: dispatchEmail
      - sqs:
          url: ${ssm:sqs-example-${opt:stage}-urlQueueSendMail}
    environment:
      urlQueueSendMail: ${ssm:sqs-example-${opt:stage}-urlQueueSendMail}
  sendMail:
    handler: src/sendMail.handler
    environment:
      userMail: ${ssm:sqs-example-${opt:stage}-userMail}
      passMail: ${ssm:sqs-example-${opt:stage}-passMail}
    events:  
      - sqs:
          arn: arn:aws:sqs:${self:custom.region}:${self:custom.id}:sqs-sa-east-1-test-dev-sendEmail
          batchSize: 10

plugins:
  - serverless-offline